<?php // this is an autogenerated file - do not edit (created 2009-12-18 12:49:21)
spl_autoload_register(
   function($class) {
      static $classes = array(
         'spriebsch\\db\\tabledatagatewayupdatetest' => '/TableDataGatewayUpdateTest.php',
         'spriebsch\\db\\databaseexceptiontest' => '/DatabaseExceptionTest.php',
         'spriebsch\\db\\tabledatagatewayinserttest' => '/TableDataGatewayInsertTest.php',
         'spriebsch\\db\\recordsetexceptiontest' => '/RecordSetExceptionTest.php',
         'spriebsch\\db\\tabledatagatewaytest' => '/TableDataGatewayTest.php',
         'spriebsch\\db\\recordsettest' => '/RecordSetTest.php',
         'spriebsch\\db\\tabledatagatewaydbfailtest' => '/TableDataGatewayDbFailTest.php',
         'spriebsch\\db\\testdatabasehandler' => '/TableDataGatewayDbFailTest.php',
         'spriebsch\\db\\testpdostatement' => '/TableDataGatewayDbFailTest.php',
         'spriebsch\\db\\databasehandlertest' => '/DatabaseHandlerTest.php',
         'spriebsch\\db\\tabledatagatewayfindtest' => '/TableDataGatewayFindTest.php',
         'spriebsch\\db\\tabledatagatewayselecttest' => '/TableDataGatewaySelectTest.php',
         'spriebsch\\db\\tabledatagatewaytestbase' => '/TableDataGatewayTestBase.php',
         'spriebsch\\db\\tabledatagatewaydeletetest' => '/TableDataGatewayDeleteTest.php'
      );
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . "/" . $classes[$cn];
      }
   }
);
?>
