<?php // this is an autogenerated file - do not edit (created 2009-12-14 15:47:11)
spl_autoload_register(
   function($class) {
      static $classes = array(
         'spriebsch\\db\\databasehandler' => '/DatabaseHandler.php',
         'spriebsch\\db\\tabledatagatewayfactory' => '/TableDataGatewayFactory.php',
         'spriebsch\\db\\databaseexception' => '/DatabaseException.php',
         'spriebsch\\db\\tabledatagateway' => '/TableDataGateway.php'
      );
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . "/" . $classes[$cn];
      }
   }
);
?>
